import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { config } from 'dotenv';

config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

await esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: 'inline',
  treeShaking: true,
  outfile: 'build/main.js',
  define: {
    'process.env.NODE_ENV': '"development"',
    'process.env.OPENAI_API_KEY': JSON.stringify(process.env.OPENAI_API_KEY || ''),
  },
  plugins: [{
    name: 'empty-module',
    setup(build) {
      build.onResolve({ filter: /^node:/ }, (args) => ({
        path: args.path.replace(/^node:/, ''),
        namespace: 'empty-module',
      }));

      build.onLoad({ filter: /.*/, namespace: 'empty-module' }, () => ({
        contents: 'export default {}; export const ReadStream = class {}; export const Readable = class {}; export const ReadableStream = class {};',
        loader: 'js',
      }));
    },
  }],
}); 